export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const POST_PROFILE_REQUEST = "POST_PROFILE_REQUEST";
export const POST_PROFILE_SUCCESS = "POST_PROFILE_SUCCESS";
export const POST_PROFILE_FAILURE = "POST_PROFILE_FAILURE";