export const GET_SYSTEM_REQUEST = "GET_SYSTEM_REQUEST";
export const GET_SYSTEM_SUCCESS = "GET_SYSTEM_SUCCESS";
export const GET_SYSTEM_FAILURE = "GET_SYSTEM_FAILURE";

export const POST_SYSTEM_REQUEST = "POST_SYSTEM_REQUEST";
export const POST_SYSTEM_SUCCESS = "POST_SYSTEM_SUCCESS";
export const POST_SYSTEM_FAILURE = "POST_SYSTEM_FAILURE";

export const EDIT_SYSTEM_REQUEST = "EDIT_SYSTEM_REQUEST";
export const EDIT_SYSTEM_SUCCESS = "EDIT_SYSTEM_SUCCESS";
export const EDIT_SYSTEM_FAILURE = "EDIT_SYSTEM_FAILURE";

export const DELETE_SYSTEM_REQUEST = "DELETE_SYSTEM_REQUEST";
export const DELETE_SYSTEM_SUCCESS = "DELETE_SYSTEM_SUCCESS";
export const DELETE_SYSTEM_FAILURE = "DELETE_SYSTEM_FAILURE";

export const GET_PROPERTIES_REQUEST = "GET_PROPERTIES_REQUEST";
export const GET_PROPERTIES_SUCCESS = "GET_PROPERTIES_SUCCESS";
export const GET_PROPERTIES_FAILURE = "GET_PROPERTIES_FAILURE";

export const POST_PROPERTIES_REQUEST = "POST_PROPERTIES_REQUEST";
export const POST_PROPERTIES_SUCCESS = "POST_PROPERTIES_SUCCESS";
export const POST_PROPERTIES_FAILURE = "POST_PROPERTIES_FAILURE";

export const EDIT_PROPERTIES_REQUEST = "EDIT_PROPERTIES_REQUEST";
export const EDIT_PROPERTIES_SUCCESS = "EDIT_PROPERTIES_SUCCESS";
export const EDIT_PROPERTIES_FAILURE = "EDIT_PROPERTIES_FAILURE";

export const DELETE_PROPERTIES_REQUEST = "DELETE_PROPERTIES_REQUEST";
export const DELETE_PROPERTIES_SUCCESS = "DELETE_PROPERTIES_SUCCESS";
export const DELETE_PROPERTIES_FAILURE = "DELETE_PROPERTIES_FAILURE";
