export const GET_SYSTEM_REQUEST = "GET_SYSTEM_REQUEST";
export const GET_SYSTEM_SUCCESS = "GET_SYSTEM_SUCCESS";
export const GET_SYSTEM_FAILURE = "GET_SYSTEM_FAILURE";

export const POST_SYSTEM_REQUEST = "POST_SYSTEM_REQUEST";
export const POST_SYSTEM_SUCCESS = "POST_SYSTEM_SUCCESS";
export const POST_SYSTEM_FAILURE = "POST_SYSTEM_FAILURE";

export const EDIT_SYSTEM_REQUEST = "EDIT_SYSTEM_REQUEST";
export const EDIT_SYSTEM_SUCCESS = "EDIT_SYSTEM_SUCCESS";
export const EDIT_SYSTEM_FAILURE = "EDIT_SYSTEM_FAILURE";

export const DELETE_SYSTEM_REQUEST = "DELETE_SYSTEM_REQUEST";
export const DELETE_SYSTEM_SUCCESS = "DELETE_SYSTEM_SUCCESS";
export const DELETE_SYSTEM_FAILURE = "DELETE_SYSTEM_FAILURE";

export const GET_PROPERTIES_REQUEST = "GET_PROPERTIES_REQUEST";
export const GET_PROPERTIES_SUCCESS = "GET_PROPERTIES_SUCCESS";
export const GET_PROPERTIES_FAILURE = "GET_PROPERTIES_FAILURE";

export const POST_PROPERTIES_REQUEST = "POST_PROPERTIES_REQUEST";
export const POST_PROPERTIES_SUCCESS = "POST_PROPERTIES_SUCCESS";
export const POST_PROPERTIES_FAILURE = "POST_PROPERTIES_FAILURE";

export const EDIT_PROPERTIES_REQUEST = "EDIT_PROPERTIES_REQUEST";
export const EDIT_PROPERTIES_SUCCESS = "EDIT_PROPERTIES_SUCCESS";
export const EDIT_PROPERTIES_FAILURE = "EDIT_PROPERTIES_FAILURE";

export const DELETE_PROPERTIES_REQUEST = "DELETE_PROPERTIES_REQUEST";
export const DELETE_PROPERTIES_SUCCESS = "DELETE_PROPERTIES_SUCCESS";
export const DELETE_PROPERTIES_FAILURE = "DELETE_PROPERTIES_FAILURE";

export const GET_AMENITIES_REQUEST = "GET_AMENITIES_REQUEST";
export const GET_AMENITIES_SUCCESS = "GET_AMENITIES_SUCCESS";
export const GET_AMENITIES_FAILURE = "GET_AMENITIES_FAILURE";

export const POST_AMENITIES_REQUEST = "POST_AMENITIES_REQUEST";
export const POST_AMENITIES_SUCCESS = "POST_AMENITIES_SUCCESS";
export const POST_AMENITIES_FAILURE = "POST_AMENITIES_FAILURE";

export const EDIT_AMENITIES_REQUEST = "EDIT_AMENITIES_REQUEST";
export const EDIT_AMENITIES_SUCCESS = "EDIT_AMENITIES_SUCCESS";
export const EDIT_AMENITIES_FAILURE = "EDIT_AMENITIES_FAILURE";

export const DELETE_AMENITIES_REQUEST = "DELETE_AMENITIES_REQUEST";
export const DELETE_AMENITIES_SUCCESS = "DELETE_AMENITIES_SUCCESS";
export const DELETE_AMENITIES_FAILURE = "DELETE_AMENITIES_FAILURE";
export const GET_UTILITIES_REQUEST = "GET_UTILITIES_REQUEST";
export const GET_UTILITIES_SUCCESS = "GET_UTILITIES_SUCCESS";
export const GET_UTILITIES_FAILURE = "GET_UTILITIES_FAILURE";

export const POST_UTILITIES_REQUEST = "POST_UTILITIES_REQUEST";
export const POST_UTILITIES_SUCCESS = "POST_UTILITIES_SUCCESS";
export const POST_UTILITIES_FAILURE = "POST_UTILITIES_FAILURE";

export const EDIT_UTILITIES_REQUEST = "EDIT_UTILITIES_REQUEST";
export const EDIT_UTILITIES_SUCCESS = "EDIT_UTILITIES_SUCCESS";
export const EDIT_UTILITIES_FAILURE = "EDIT_UTILITIES_FAILURE";

export const DELETE_UTILITIES_REQUEST = "DELETE_UTILITIES_REQUEST";
export const DELETE_UTILITIES_SUCCESS = "DELETE_UTILITIES_SUCCESS";
export const DELETE_UTILITIES_FAILURE = "DELETE_UTILITIES_FAILURE";
export const GET_UNIT_REQUEST = "GET_UNIT_REQUEST";
export const GET_UNIT_SUCCESS = "GET_UNIT_SUCCESS";
export const GET_UNIT_FAILURE = "GET_UNIT_FAILURE";

export const POST_UNIT_REQUEST = "POST_UNIT_REQUEST";
export const POST_UNIT_SUCCESS = "POST_UNIT_SUCCESS";
export const POST_UNIT_FAILURE = "POST_UNIT_FAILURE";

export const EDIT_UNIT_REQUEST = "EDIT_UNIT_REQUEST";
export const EDIT_UNIT_SUCCESS = "EDIT_UNIT_SUCCESS";
export const EDIT_UNIT_FAILURE = "EDIT_UNIT_FAILURE";

export const DELETE_UNIT_REQUEST = "DELETE_UNIT_REQUEST";
export const DELETE_UNIT_SUCCESS = "DELETE_UNIT_SUCCESS";
export const DELETE_UNIT_FAILURE = "DELETE_UNIT_FAILURE";

export const GET_AMOUNT_REQUEST = "GET_AMOUNT_REQUEST";
export const GET_AMOUNT_SUCCESS = "GET_AMOUNT_SUCCESS";
export const GET_AMOUNT_FAILURE = "GET_AMOUNT_FAILURE";

export const POST_AMOUNT_REQUEST = "POST_AMOUNT_REQUEST";
export const POST_AMOUNT_SUCCESS = "POST_AMOUNT_SUCCESS";
export const POST_AMOUNT_FAILURE = "POST_AMOUNT_FAILURE";

export const EDIT_AMOUNT_REQUEST = "EDIT_AMOUNT_REQUEST";
export const EDIT_AMOUNT_SUCCESS = "EDIT_AMOUNT_SUCCESS";
export const EDIT_AMOUNT_FAILURE = "EDIT_AMOUNT_FAILURE";

export const DELETE_AMOUNT_REQUEST = "DELETE_AMOUNT_REQUEST";
export const DELETE_AMOUNT_SUCCESS = "DELETE_AMOUNT_SUCCESS";
export const DELETE_AMOUNT_FAILURE = "DELETE_AMOUNT_FAILURE";

export const GET_USER_ROLE_REQUEST = "GET_USER_ROLE_REQUEST";
export const GET_USER_ROLE_SUCCESS = "GET_USER_ROLE_SUCCESS";
export const GET_USER_ROLE_FAILURE = "GET_USER_ROLE_FAILURE";

export const POST_USER_ROLE_REQUEST = "POST_USER_ROLE_REQUEST";
export const POST_USER_ROLE_SUCCESS = "POST_USER_ROLE_SUCCESS";
export const POST_USER_ROLE_FAILURE = "POST_USER_ROLE_FAILURE";

export const EDIT_USER_ROLE_REQUEST = "EDIT_USER_ROLE_REQUEST";
export const EDIT_USER_ROLE_SUCCESS = "EDIT_USER_ROLE_SUCCESS";
export const EDIT_USER_ROLE_FAILURE = "EDIT_USER_ROLE_FAILURE";

export const DELETE_USER_ROLE_REQUEST = "DELETE_USER_ROLE_REQUEST";
export const DELETE_USER_ROLE_SUCCESS = "DELETE_USER_ROLE_SUCCESS";
export const DELETE_USER_ROLE_FAILURE = "DELETE_USER_ROLE_FAILURE";

export const GET_ROLE_REQUEST = "GET_ROLE_REQUEST";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const GET_ROLE_FAILURE = "GET_ROLE_FAILURE";

export const POST_ROLE_REQUEST = "POST_ROLE_REQUEST";
export const POST_ROLE_SUCCESS = "POST_ROLE_SUCCESS";
export const POST_ROLE_FAILURE = "POST_ROLE_FAILURE";

export const EDIT_ROLE_REQUEST = "EDIT_ROLE_REQUEST";
export const EDIT_ROLE_SUCCESS = "EDIT_ROLE_SUCCESS";
export const EDIT_ROLE_FAILURE = "EDIT_ROLE_FAILURE";

export const DELETE_ROLE_REQUEST = "DELETE_ROLE_REQUEST";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAILURE = "DELETE_ROLE_FAILURE";
export const GET_PERMISSION_REQUEST = "GET_PERMISSION_REQUEST";
export const GET_PERMISSION_SUCCESS = "GET_PERMISSION_SUCCESS";
export const GET_PERMISSION_FAILURE = "GET_PERMISSION_FAILURE";

export const POST_PERMISSION_REQUEST = "POST_PERMISSION_REQUEST";
export const POST_PERMISSION_SUCCESS = "POST_PERMISSION_SUCCESS";
export const POST_PERMISSION_FAILURE = "POST_PERMISSION_FAILURE";

export const EDIT_PERMISSION_REQUEST = "EDIT_PERMISSION_REQUEST";
export const EDIT_PERMISSION_SUCCESS = "EDIT_PERMISSION_SUCCESS";
export const EDIT_PERMISSION_FAILURE = "EDIT_PERMISSION_FAILURE";

export const DELETE_PERMISSION_REQUEST = "DELETE_PERMISSION_REQUEST";
export const DELETE_PERMISSION_SUCCESS = "DELETE_PERMISSION_SUCCESS";
export const DELETE_PERMISSION_FAILURE = "DELETE_PERMISSION_FAILURE";
export const GET_TENTANTS_REQUEST = "GET_TENTANTS_REQUEST";
export const GET_TENTANTS_SUCCESS = "GET_TENTANTS_SUCCESS";
export const GET_TENTANTS_FAILURE = "GET_TENTANTS_FAILURE";

export const POST_TENTANTS_REQUEST = "POST_TENTANTS_REQUEST";
export const POST_TENTANTS_SUCCESS = "POST_TENTANTS_SUCCESS";
export const POST_TENTANTS_FAILURE = "POST_TENTANTS_FAILURE";

export const EDIT_TENTANTS_REQUEST = "EDIT_TENTANTS_REQUEST";
export const EDIT_TENTANTS_SUCCESS = "EDIT_TENTANTS_SUCCESS";
export const EDIT_TENTANTS_FAILURE = "EDIT_TENTANTS_FAILURE";

export const DELETE_TENTANTS_REQUEST = "DELETE_TENTANTS_REQUEST";
export const DELETE_TENTANTS_SUCCESS = "DELETE_TENTANTS_SUCCESS";
export const DELETE_TENTANTS_FAILURE = "DELETE_TENTANTS_FAILURE";


export const GET_LEASETYPES_REQUEST = "GET_LEASETYPES_REQUEST";
export const GET_LEASETYPES_SUCCESS = "GET_LEASETYPES_SUCCESS";
export const GET_LEASETYPES_FAILURE = "GET_LEASETYPES_FAILURE";

export const POST_LEASETYPES_REQUEST = "POST_LEASETYPES_REQUEST";
export const POST_LEASETYPES_SUCCESS = "POST_LEASETYPES_SUCCESS";
export const POST_LEASETYPES_FAILURE = "POST_LEASETYPES_FAILURE";

export const EDIT_LEASETYPES_REQUEST = "EDIT_LEASETYPES_REQUEST";
export const EDIT_LEASETYPES_SUCCESS = "EDIT_LEASETYPES_SUCCESS";
export const EDIT_LEASETYPES_FAILURE = "EDIT_LEASETYPES_FAILURE";

export const DELETE_LEASETYPES_REQUEST = "DELETE_LEASETYPES_REQUEST";
export const DELETE_LEASETYPES_SUCCESS = "DELETE_LEASETYPES_SUCCESS";
export const DELETE_LEASETYPES_FAILURE = "DELETE_LEASETYPES_FAILURE";

export const GET_EXTRACHARGE_REQUEST = "GET_EXTRACHARGE_REQUEST";
export const GET_EXTRACHARGE_SUCCESS = "GET_EXTRACHARGE_SUCCESS";
export const GET_EXTRACHARGE_FAILURE = "GET_EXTRACHARGE_FAILURE";

export const POST_EXTRACHARGE_REQUEST = "POST_EXTRACHARGE_REQUEST";
export const POST_EXTRACHARGE_SUCCESS = "POST_EXTRACHARGE_SUCCESS";
export const POST_EXTRACHARGE_FAILURE = "POST_EXTRACHARGE_FAILURE";

export const EDIT_EXTRACHARGE_REQUEST = "EDIT_EXTRACHARGE_REQUEST";
export const EDIT_EXTRACHARGE_SUCCESS = "EDIT_EXTRACHARGE_SUCCESS";
export const EDIT_EXTRACHARGE_FAILURE = "EDIT_EXTRACHARGE_FAILURE";

export const DELETE_EXTRACHARGE_REQUEST = "DELETE_EXTRACHARGE_REQUEST";
export const DELETE_EXTRACHARGE_SUCCESS = "DELETE_EXTRACHARGE_SUCCESS";
export const DELETE_EXTRACHARGE_FAILURE = "DELETE_EXTRACHARGE_FAILURE";