export const GET_UTILITY_REQUEST = "GET_UTILITY_REQUEST";
export const GET_UTILITY_SUCCESS = "GET_UTILITY_SUCCESS";
export const GET_UTILITY_FAILURE = "GET_UTILITY_FAILURE";

export const POST_UTILITY_REQUEST = "POST_UTILITY_REQUEST";
export const POST_UTILITY_SUCCESS = "POST_UTILITY_SUCCESS";
export const POST_UTILITY_FAILURE = "POST_UTILITY_FAILURE";

export const EDIT_UTILITY_REQUEST = "EDIT_UTILITY_REQUEST";
export const EDIT_UTILITY_SUCCESS = "EDIT_UTILITY_SUCCESS";
export const EDIT_UTILITY_FAILURE = "EDIT_UTILITY_FAILURE";

export const DELETE_UTILITY_REQUEST = "DELETE_UTILITY_REQUEST";
export const DELETE_UTILITY_SUCCESS = "DELETE_UTILITY_SUCCESS";
export const DELETE_UTILITY_FAILURE = "DELETE_UTILITY_FAILURE";
