export const GET_PAYMENT_REQUEST = "GET_PAYMENT_REQUEST";
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
export const GET_PAYMENT_FAILURE = "GET_PAYMENT_FAILURE";

export const POST_PAYMENT_REQUEST = "POST_PAYMENT_REQUEST";
export const POST_PAYMENT_SUCCESS = "POST_PAYMENT_SUCCESS";
export const POST_PAYMENT_FAILURE = "POST_PAYMENT_FAILURE";

export const EDIT_PAYMENT_REQUEST = "EDIT_PAYMENT_REQUEST";
export const EDIT_PAYMENT_SUCCESS = "EDIT_PAYMENT_SUCCESS";
export const EDIT_PAYMENT_FAILURE = "EDIT_PAYMENT_FAILURE";

export const DELETE_PAYMENT_REQUEST = "DELETE_PAYMENT_REQUEST";
export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_FAILURE = "DELETE_PAYMENT_FAILURE";
