export const GET_PROPERTY_REQUEST = "GET_PROPERTY_REQUEST";
export const GET_PROPERTY_SUCCESS = "GET_PROPERTY_SUCCESS";
export const GET_PROPERTY_FAILURE = "GET_PROPERTY_FAILURE";

export const POST_PROPERTY_REQUEST = "POST_PROPERTY_REQUEST";
export const POST_PROPERTY_SUCCESS = "POST_PROPERTY_SUCCESS";
export const POST_PROPERTY_FAILURE = "POST_PROPERTY_FAILURE";

export const EDIT_PROPERTY_REQUEST = "EDIT_PROPERTY_REQUEST";
export const EDIT_PROPERTY_SUCCESS = "EDIT_PROPERTY_SUCCESS";
export const EDIT_PROPERTY_FAILURE = "EDIT_PROPERTY_FAILURE";

export const DELETE_PROPERTY_REQUEST = "DELETE_PROPERTY_REQUEST";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_FAILURE = "DELETE_PROPERTY_FAILURE";