export const GET_PROPERTY_REQUEST = "GET_PROPERTY_REQUEST";
export const GET_PROPERTY_SUCCESS = "GET_PROPERTY_SUCCESS";
export const GET_PROPERTY_FAILURE = "GET_PROPERTY_FAILURE";

export const POST_PROPERTY_REQUEST = "POST_PROPERTY_REQUEST";
export const POST_PROPERTY_SUCCESS = "POST_PROPERTY_SUCCESS";
export const POST_PROPERTY_FAILURE = "POST_PROPERTY_FAILURE";

export const EDIT_PROPERTY_REQUEST = "EDIT_PROPERTY_REQUEST";
export const EDIT_PROPERTY_SUCCESS = "EDIT_PROPERTY_SUCCESS";
export const EDIT_PROPERTY_FAILURE = "EDIT_PROPERTY_FAILURE";

export const DELETE_PROPERTY_REQUEST = "DELETE_PROPERTY_REQUEST";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_FAILURE = "DELETE_PROPERTY_FAILURE";

export const GET_UNIT_REQUEST = "GET_UNIT_REQUEST";
export const GET_UNIT_SUCCESS = "GET_UNIT_SUCCESS";
export const GET_UNIT_FAILURE = "GET_UNIT_FAILURE";

export const POST_UNIT_REQUEST = "POST_UNIT_REQUEST";
export const POST_UNIT_SUCCESS = "POST_UNIT_SUCCESS";
export const POST_UNIT_FAILURE = "POST_UNIT_FAILURE";

export const EDIT_UNIT_REQUEST = "EDIT_UNIT_REQUEST";
export const EDIT_UNIT_SUCCESS = "EDIT_UNIT_SUCCESS";
export const EDIT_UNIT_FAILURE = "EDIT_UNIT_FAILURE";

export const DELETE_UNIT_REQUEST = "DELETE_UNIT_REQUEST";
export const DELETE_UNIT_SUCCESS = "DELETE_UNIT_SUCCESS";
export const DELETE_UNIT_FAILURE = "DELETE_UNIT_FAILURE";

export const ADD_MODAL = "ADD_MODAL";
export const DELETE_MODAL = "DELETE_MODAL";

export const ADD_PAYMENT_MODAL = "ADD_PAYMENT_MODAL";
export const DELETE_PAYMENT_MODAL = "DELETE_PAYMENT_MODAL";

export const ADD_EXTRA_MODAL = "ADD_EXTRA_MODAL";
export const DELETE_EXTRA_MODAL = "DELETE_EXTRA_MODAL";
export const ADD_LATEFINE_MODAL = "ADD_LATEFINE_MODAL";
export const DELETE_LATEFINE_MODAL = "DELETE_LATEFINE_MODAL";
export const ADD_UTILITY_MODAL = "ADD_UTILITY_MODAL";
export const DELETE_UTILITY_MODAL = "DELETE_UTILITY_MODAL";