export const SIGNUP_REQUEST="SIGNUP_REQUEST";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const SIGNUP_FAILURE="SIGNUP_FAILURE";


export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const OWNER_LOGIN_REQUEST="OWNER_LOGIN_REQUEST";
export const OWNER_LOGIN_SUCCESS ="OWNER_LOGIN_SUCCESS";
export const OWNER_LOGIN_FAILURE ="OWNER_LOGIN_FAILURE";

export const FORGET_PASSWORD_REQUEST ="FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAILURE = "FORGET_PASSWORD_FAILURE";

export const GET_RESET_PASSWORD_REQUEST = "GET_RESET_PASSWORD_REQUEST";
export const GET_RESET_PASSWORD_SUCCESS = "GET_RESET_PASSWORD_SUCCESS";
export const GET_RESET_PASSWORD_FAILURE = "GET_RESET_PASSWORD_FAILURE";

export const POST_RESET_PASSWORD_REQUEST = "POST_RESET_PASSWORD_REQUEST";
export const POST_RESET_PASSWORD_SUCCESS = "POST_RESET_PASSWORD_SUCCESS";
export const POST_RESET_PASSWORD_FAILURE = "POST_RESET_PASSWORD_FAILURE";

export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';

export const ROLES = "ROLES"
