export const GET_VACATENOTICE_REQUEST = "GET_VACATENOTICE_REQUEST";
export const GET_VACATENOTICE_SUCCESS = "GET_VACATENOTICE_SUCCESS";
export const GET_VACATENOTICE_FAILURE = "GET_VACATENOTICE_FAILURE";

export const POST_VACATENOTICE_REQUEST = "POST_VACATENOTICE_REQUEST";
export const POST_VACATENOTICE_SUCCESS = "POST_VACATENOTICE_SUCCESS";
export const POST_VACATENOTICE_FAILURE = "POST_VACATENOTICE_FAILURE";

export const EDIT_VACATENOTICE_REQUEST = "EDIT_VACATENOTICE_REQUEST";
export const EDIT_VACATENOTICE_SUCCESS = "EDIT_VACATENOTICE_SUCCESS";
export const EDIT_VACATENOTICE_FAILURE = "EDIT_VACATENOTICE_FAILURE";

export const DELETE_VACATENOTICE_REQUEST = "DELETE_VACATENOTICE_REQUEST";
export const DELETE_VACATENOTICE_SUCCESS = "DELETE_VACATENOTICE_SUCCESS";
export const DELETE_VACATENOTICE_FAILURE = "DELETE_VACATENOTICE_FAILURE";

export const GET_INVOICE_REQUEST = "GET_INVOICE_REQUEST";
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS";
export const GET_INVOICE_FAILURE = "GET_INVOICE_FAILURE";

export const POST_INVOICE_REQUEST = "POST_INVOICE_REQUEST";
export const POST_INVOICE_SUCCESS = "POST_INVOICE_SUCCESS";
export const POST_INVOICE_FAILURE = "POST_INVOICE_FAILURE";

export const EDIT_INVOICE_REQUEST = "EDIT_INVOICE_REQUEST";
export const EDIT_INVOICE_SUCCESS = "EDIT_INVOICE_SUCCESS";
export const EDIT_INVOICE_FAILURE = "EDIT_INVOICE_FAILURE";

export const DELETE_INVOICE_REQUEST = "DELETE_INVOICE_REQUEST";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAILURE = "DELETE_INVOICE_FAILURE";