export const GET_LANDLORD_REQUEST ="GET_LANDLORD_REQUEST";
export const GET_LANDLORD_SUCCESS = "GET_LANDLORD_SUCCESS";
export const GET_LANDLORD_FAILURE = "GET_LANDLORD_FAILURE";

export const POST_LANDLORD_REQUEST = "POST_LANDLORD_REQUEST";
export const POST_LANDLORD_SUCCESS = "POST_LANDLORD_SUCCESS";
export const POST_LANDLORD_FAILURE = "POST_LANDLORD_FAILURE";

export const EDIT_LANDLORD_REQUEST = "EDIT_LANDLORD_REQUEST";
export const EDIT_LANDLORD_SUCCESS = "EDIT_LANDLORD_SUCCESS";
export const EDIT_LANDLORD_FAILURE = "EDIT_LANDLORD_FAILURE";