export const GET_LANDLORD_REQUEST ="GET_LANDLORD_REQUEST";
export const GET_LANDLORD_SUCCESS = "GET_LANDLORD_SUCCESS";
export const GET_LANDLORD_FAILURE = "GET_LANDLORD_FAILURE";

export const POST_LANDLORD_REQUEST = "POST_LANDLORD_REQUEST";
export const POST_LANDLORD_SUCCESS = "POST_LANDLORD_SUCCESS";
export const POST_LANDLORD_FAILURE = "POST_LANDLORD_FAILURE";

export const EDIT_LANDLORD_REQUEST = "EDIT_LANDLORD_REQUEST";
export const EDIT_LANDLORD_SUCCESS = "EDIT_LANDLORD_SUCCESS";
export const EDIT_LANDLORD_FAILURE = "EDIT_LANDLORD_FAILURE";

export const DELETE_LANDLORD_REQUEST = "DELETE_LANDLORD_REQUEST";
export const DELETE_LANDLORD_SUCCESS = "DELETE_LANDLORD_SUCCESS";
export const DELETE_LANDLORD_FAILURE = "DELETE_LANDLORD_FAILURE";

export const SET_PAGINATION = "SET_PAGINATION" 

export const FETCH_LANDLORDS_REQUEST = "FETCH_LANDLORDS_REQUEST";
export const FETCH_LANDLORDS_SUCCESS = "FETCH_LANDLORDS_SUCCESS";
export const FETCH_LANDLORDS_FAILURE = "FETCH_LANDLORDS_FAILURE";

export const GET_APARTMENT_REQUEST ="GET_APARTMENT_REQUEST";
export const GET_APARTMENT_SUCCESS = "GET_APARTMENT_SUCCESS";
export const GET_APARTMENT_FAILURE = "GET_APARTMENT_FAILURE";

export const SUPERADMIN_APARTMENT_REQUEST = "SUPERADMIN_APARTMENT_REQUEST";
export const SUPERADMIN_APARTMENT_SUCCESS = "SUPERADMIN_APARTMENT_SUCCESS";
export const SUPERADMIN_APARTMENT_FAILURE = "SUPERADMIN_APARTMENT_FAILURE";

export const POST_APARTMENT_REQUEST = "POST_APARTMENT_REQUEST";
export const POST_APARTMENT_SUCCESS = "POST_APARTMENT_SUCCESS";
export const POST_APARTMENT_FAILURE = "POST_APARTMENT_FAILURE";

export const EDIT_APARTMENT_REQUEST = "EDIT_APARTMENT_REQUEST";
export const EDIT_APARTMENT_SUCCESS = "EDIT_APARTMENT_SUCCESS";
export const EDIT_APARTMENT_FAILURE = "EDIT_APARTMENT_FAILURE";

export const DELETE_APARTMENT_REQUEST = "DELETE_APARTMENT_REQUEST";
export const DELETE_APARTMENT_SUCCESS = "DELETE_APARTMENT_SUCCESS";
export const DELETE_APARTMENT_FAILURE = "DELETE_APARTMENT_FAILURE";