export const GET_LEASE_REQUEST = "GET_LEASE_REQUEST";
export const GET_LEASE_SUCCESS = "GET_LEASE_SUCCESS";
export const GET_LEASE_FAILURE = "GET_LEASE_FAILURE";

export const POST_LEASE_REQUEST = "POST_LEASE_REQUEST";
export const POST_LEASE_SUCCESS = "POST_LEASE_SUCCESS";
export const POST_LEASE_FAILURE = "POST_LEASE_FAILURE";

export const EDIT_LEASE_REQUEST = "EDIT_LEASE_REQUEST";
export const EDIT_LEASE_SUCCESS = "EDIT_LEASE_SUCCESS";
export const EDIT_LEASE_FAILURE = "EDIT_LEASE_FAILURE";

export const DELETE_LEASE_REQUEST = "DELETE_LEASE_REQUEST";
export const DELETE_LEASE_SUCCESS = "DELETE_LEASE_SUCCESS";
export const DELETE_LEASE_FAILURE = "DELETE_LEASE_FAILURE";
