export const GET_TENTANTS_REQUEST = "GET_TENTANTS_REQUEST";
export const GET_TENTANTS_SUCCESS = "GET_TENTANTS_SUCCESS";
export const GET_TENTANTS_FAILURE = "GET_TENTANTS_FAILURE";

export const POST_TENTANTS_REQUEST = "POST_TENTANTS_REQUEST";
export const POST_TENTANTS_SUCCESS = "POST_TENTANTS_SUCCESS";
export const POST_TENTANTS_FAILURE = "POST_TENTANTS_FAILURE";

export const EDIT_TENTANTS_REQUEST = "EDIT_TENTANTS_REQUEST";
export const EDIT_TENTANTS_SUCCESS = "EDIT_TENTANTS_SUCCESS";
export const EDIT_TENTANTS_FAILURE = "EDIT_TENTANTS_FAILURE";

export const DELETE_TENTANTS_REQUEST = "DELETE_TENTANTS_REQUEST";
export const DELETE_TENTANTS_SUCCESS = "DELETE_TENTANTS_SUCCESS";
export const DELETE_TENTANTS_FAILURE = "DELETE_TENTANTS_FAILURE";

export const GET_NOTIFICATION_TENTANTS_REQUEST = "GET_NOTIFICATION_TENTANTS_REQUEST";
export const GET_NOTIFICATION_TENTANTS_SUCCESS = "GET_NOTIFICATION_TENTANTS_SUCCESS";
export const GET_NOTIFICATION_TENTANTS_FAILURE ="GET_NOTIFICATION_TENTANTS_FAILURE";

export const EDIT_NOTIFICATION_TENTANTS_REQUEST = "EDIT_NOTIFICATION_TENTANTS_REQUEST";
export const EDIT_NOTIFICATION_TENTANTS_SUCCESS = "EDIT_NOTIFICATION_TENTANTS_SUCCESS";
export const EDIT_NOTIFICATION_TENTANTS_FAILURE = "EDIT_NOTIFICATION_TENTANTS_FAILURE";